### ISSUE TITLE
grunt server error

### ISSUE THREAD

**Issue by tharrington** [rayokota/generator-angular-sinatra#4]
I have the rackup service running and load grunt server, but I am getting this error:

Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "server" not found. Use --force to continue.

Aborted due to warnings.

Also, how can I get the rackup server to livereload?

**Comment by rayokota** [comment]
Fixed by upgrade of grunt-connect-proxy
